- name: Tap homebrew repositories
  homebrew_tap: name={{ item }} state=present
  with_items:
    - caskroom/cask
    - homebrew/core

- name: Update and upgrade Homebrew
  shell: brew update && brew upgrade && brew cleanup

- name: Install openssh with Homebrew
  homebrew: name=openssh state=latest install_options=with-keychain-support
- block:
  - name: Install libraries with Homebrew cask
    homebrew_cask: name={{ item }}
    with_items:
     - appcode
     - android-studio
     - docker
     - google-chrome
     - slack
     - gyazo
     - postman
     - iterm2
     - visual-studio-code
     - sublime-text
     - spectacle
     - java8
     - intellij-idea
     - ngrok
     - skype
     - spotify
     - transmission
     - vagrant
     - virtualbox
     - vlc
  ignore_errors: yes

- block:
  - name: Install libraries with Homebrew
    homebrew: name={{ item }} state=latest
    with_items:
      - awscli
      - awsebcli
      - bash-completion
      - boot-clj
      - cocoapods
      - direnv
      - gnupg2
      - heroku
      - imagemagick
      - markdown
      - neovim
      - nvm
      - packer
      - postgresql
      - pyenv
      - rbenv
      - rlwrap
      - ruby
      - terraform
      - tmux
      - watchman
      - wget
      - yarn
  ignore_errors: yes

- block:
  - name: Install Java libs
    homebrew: name={{ item }} state=latest
    with_items:
      - flyway
      - leiningen
      - maven
  ignore_errors: yes

- name: Install Apex
  command: bash -c "curl https://raw.githubusercontent.com/apex/apex/master/install.sh | sh"

- block:
  - name: Install Jekyll
    command: bash -c "gem install jekyll bundler"
  ignore_errors: yes

- block:
  - name: upgrade pip
    shell: pip install --upgrade pip
    become: true
  ignore_errors: yes

- block:
  - name: install virtualenv
    shell: pip install virtualenv
    become: true
  ignore_errors: yes

- block:
  - name: Install "react-native-cli" node.js package.
    npm:
      name: react-native-cli
      global: yes
  ignore_errors: yes

- block:
  - name: Install "re-natal" node.js package.
    npm:
      name: re-natal
      global: yes
  ignore_errors: yes

- block:
  - name: Install "react-devtools" node.js package.
    npm:
      name: react-devtools
      global: yes
  ignore_errors: yes

- block:
  - name: Install "phantomjs" node.js package.
    npm:
      name: phantomjs
      global: yes
  ignore_errors: yes
