- hosts: targets
  gather_facts: False
  vars:
    editor: "VIM"
    user_name: "<GIT USER NAME HERE>"
    email: "<GIT EMAIL HERE>"
  tasks:
    - include: tasks/dependencies.yml
    - include: tasks/dotfiles.yml
    - name: "Setup emacs editor"
      include: tasks/emacs.yml
      when: editor == "EMACS"
    - name: "Setup vim editor"
      include: tasks/vim.yml
      when: editor == "VIM"
    - include: tasks/golang.yml
    - include: tasks/mac_settings.yml
